eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
  
  
name: "vijay"
limits.service.minimum=2
limits.service.maximum=1000
